# Generated by Django 5.0.1 on 2024-01-28 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='joke',
            options={'verbose_name': 'Анекдот', 'verbose_name_plural': 'Анекдоты'},
        ),
    ]
